from __future__ import annotations

from pathlib import Path


def _prompt(prompt: str, default: str = "") -> str:
    """
    Read a line of user input, displaying an optional default value in brackets.
    
    Parameters:
        prompt (str): Text shown to the user as the prompt.
        default (str): Fallback value displayed in brackets and returned if the user submits an empty line.
    
    Returns:
        str: The user's input with surrounding whitespace removed, or `default` if the input is empty.
    """
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def render_config(
    upload_root: str,
    max_bytes: int,
    project_name: str,
    webhook: str,
    app_id: str,
    app_secret: str,
    app_token: str,
    table_id: str,
    parent_node: str,
) -> str:
    """
    Render a Python configuration file content for the general-bug-report project using the provided values.
    
    Parameters:
        upload_root (str): Path used for storing uploaded files (assigned to UPLOAD_ROOT).
        max_bytes (int): Maximum upload size in bytes (assigned to MAX_BYTES).
        project_name (str): Key name for the PROJECTS mapping to configure project-specific values.
        webhook (str): Default webhook URL (assigned to DEFAULT_WEBHOOK).
        app_id (str): Default Bitable app ID (assigned to DEFAULT_APP_ID).
        app_secret (str): Default Bitable app secret (assigned to DEFAULT_APP_SECRET).
        app_token (str): Default Bitable app token (assigned to DEFAULT_BITABLE_APP_TOKEN).
        table_id (str): Default Bitable table ID (assigned to DEFAULT_BITABLE_TABLE_ID).
        parent_node (str): Default Bitable parent node (assigned to DEFAULT_BITABLE_PARENT_NODE).
    
    Returns:
        str: A multi-line string containing a complete Python configuration file with constants,
        allowed-extension sets, default field mappings, DEFAULT_CONSTANTS, and a PROJECTS entry
        populated using the provided arguments.
    """
    return f'''"""Generated by general-bug-report-init-config."""

UPLOAD_ROOT = "{upload_root}"
MAX_BYTES = {max_bytes}

ALLOWED_LOG_EXT = {{".log", ".zip", ".txt"}}
ALLOWED_SAVE_EXT = {{".zip", ".sav"}}
ALLOWED_IMG_EXT = {{".jpg", ".jpeg", ".png"}}
ALLOWED_FILES_EXT = {{".zip"}}

DEFAULT_WEBHOOK = "{webhook}"
DEFAULT_APP_ID = "{app_id}"
DEFAULT_APP_SECRET = "{app_secret}"
DEFAULT_BITABLE_APP_TOKEN = "{app_token}"
DEFAULT_BITABLE_TABLE_ID = "{table_id}"
DEFAULT_BITABLE_PARENT_NODE = "{parent_node}"

DEFAULT_FIELDS_MAP = {{
    "bug_title": "Bug Title",
    "version": "Version",
    "bug_type": "Bug Type",
    "stable": "Stable Reproducible",
    "player_id": "Player ID",
    "hardware": "Hardware",
    "name": "Name",
    "contact": "Contact",
    "description": "Description",
    "received": "Upload Time",
    "category": "Category",
    "files": "Files",
    "screenshot": "Screenshot",
}}

DEFAULT_CONSTANTS = {{"category_value": "Bug"}}

PROJECTS = {{
    "{project_name}": {{
        "webhook": DEFAULT_WEBHOOK,
        "bitable": {{
            "app_id": DEFAULT_APP_ID,
            "app_secret": DEFAULT_APP_SECRET,
            "app_token": DEFAULT_BITABLE_APP_TOKEN,
            "table_id": DEFAULT_BITABLE_TABLE_ID,
            "parent_node": DEFAULT_BITABLE_PARENT_NODE,
        }},
        "fields_override": {{}},
        "constants_override": {{}},
    }}
}}
'''


def init_config(target: Path = Path("config.py")) -> Path:
    """
    Interactively collect configuration values and write a generated config file to the given path.
    
    Prompts the user for upload settings, project name, webhook and Bitable credentials, renders a configuration file from those values, writes it to `target`, and returns the path.
    
    Parameters:
        target (Path): Filesystem path where the generated configuration will be written (defaults to "config.py").
    
    Returns:
        Path: The same `target` path after the file has been written.
    """
    print("Configure general-bug-report step by step.")
    upload_root = _prompt("UPLOAD_ROOT", "./uploads")
    max_bytes = int(_prompt("MAX_BYTES", str(6 * 1024 * 1024)))

    project_name = _prompt("PROJECT name", "demo")
    webhook = _prompt("DEFAULT_WEBHOOK (optional)", "")
    app_id = _prompt("DEFAULT_APP_ID")
    app_secret = _prompt("DEFAULT_APP_SECRET")
    app_token = _prompt("DEFAULT_BITABLE_APP_TOKEN")
    table_id = _prompt("DEFAULT_BITABLE_TABLE_ID")
    parent_node = _prompt("DEFAULT_BITABLE_PARENT_NODE")

    content = render_config(
        upload_root=upload_root,
        max_bytes=max_bytes,
        project_name=project_name,
        webhook=webhook,
        app_id=app_id,
        app_secret=app_secret,
        app_token=app_token,
        table_id=table_id,
        parent_node=parent_node,
    )

    target.write_text(content)
    print(f"Wrote {target}")
    return target


if __name__ == "__main__":
    init_config()
