from __future__ import annotations

from pathlib import Path


def _prompt(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _default_upload_root(project_name: str) -> str:
    return f"./uploads/{project_name}"


def render_config(
    upload_root: str,
    max_bytes: int,
    project_name: str,
    webhook: str,
    app_id: str,
    app_secret: str,
    app_token: str,
    table_id: str,
    parent_node: str,
) -> str:
    return f'''"""Generated by general-bug-report-init-config."""

UPLOAD_ROOT = "{upload_root}"
MAX_BYTES = {max_bytes}

ALLOWED_LOG_EXT = {{".log", ".zip", ".txt"}}
ALLOWED_SAVE_EXT = {{".zip", ".sav"}}
ALLOWED_IMG_EXT = {{".jpg", ".jpeg", ".png"}}
ALLOWED_FILES_EXT = {{".zip"}}

DEFAULT_WEBHOOK = "{webhook}"
DEFAULT_APP_ID = "{app_id}"
DEFAULT_APP_SECRET = "{app_secret}"
DEFAULT_BITABLE_APP_TOKEN = "{app_token}"
DEFAULT_BITABLE_TABLE_ID = "{table_id}"
DEFAULT_BITABLE_PARENT_NODE = "{parent_node}"

DEFAULT_FIELDS_MAP = {{
    "bug_title": "Bug Title",
    "version": "Version",
    "bug_type": "Bug Type",
    "stable": "Stable Reproducible",
    "player_id": "Player ID",
    "hardware": "Hardware",
    "name": "Name",
    "contact": "Contact",
    "description": "Description",
    "received": "Upload Time",
    "category": "Category",
    "files": "Files",
    "screenshot": "Screenshot",
}}

DEFAULT_CONSTANTS = {{"category_value": "Bug"}}

PROJECTS = {{
    "{project_name}": {{
        "webhook": DEFAULT_WEBHOOK,
        "bitable": {{
            "app_id": DEFAULT_APP_ID,
            "app_secret": DEFAULT_APP_SECRET,
            "app_token": DEFAULT_BITABLE_APP_TOKEN,
            "table_id": DEFAULT_BITABLE_TABLE_ID,
            "parent_node": DEFAULT_BITABLE_PARENT_NODE,
        }},
        "fields_override": {{}},
        "constants_override": {{}},
    }}
}}
'''


def init_config(target: Path = Path("config.py")) -> Path:
    print("Configure general-bug-report step by step.")
    project_name = _prompt("PROJECT name", "demo")
    upload_root = _prompt("UPLOAD_ROOT", _default_upload_root(project_name))
    max_bytes = int(_prompt("MAX_BYTES", str(6 * 1024 * 1024)))

    webhook = _prompt("DEFAULT_WEBHOOK (optional)", "")
    app_id = _prompt("DEFAULT_APP_ID")
    app_secret = _prompt("DEFAULT_APP_SECRET")
    app_token = _prompt("DEFAULT_BITABLE_APP_TOKEN")
    table_id = _prompt("DEFAULT_BITABLE_TABLE_ID")
    parent_node = _prompt("DEFAULT_BITABLE_PARENT_NODE")

    content = render_config(
        upload_root=upload_root,
        max_bytes=max_bytes,
        project_name=project_name,
        webhook=webhook,
        app_id=app_id,
        app_secret=app_secret,
        app_token=app_token,
        table_id=table_id,
        parent_node=parent_node,
    )

    target.write_text(content)
    print(f"Wrote {target}")
    return target


if __name__ == "__main__":
    init_config()
